---
version: "2"

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  disable:
    - errcheck
    - staticcheck
    - unused

# see: https://golangci-lint.run/usage/configuration/
