sudo: false
language: go
go:
  - 1.7
  - 1.8
  - 1.9
  - "1.10"
  - 1.11
  - 1.12
  - 1.13
  - tip
before_install:
  - |
    if expr $TRAVIS_GO_VERSION : 1\.11 > /dev/null; then
      echo "Remove go.sum in order to avoid checksum mismatch go 1.11. Go changed how to calculate checksum."
      rm go.sum go.mod
    fi

script:
  - go test -v ./...

env:
  - GO111MODULE=on
